### ISSUE TITLE
Tests for the iOS target pass in Xcode but fail on the command line

### ISSUE THREAD

**Issue by paulyoung** [imgflo/ImgFlo.swift#1]
I suspect this is an issue with `xcodebuild`.

**Comment by paulyoung** [comment]
I should note that 2 of the 5 tests are failing on the command line as opposed to all 5 passing when using Xcode.

**Comment by nickvelloff** [comment]
@paulyoung who are we looking for help from on this?

**Comment by paulyoung** [comment]
Anyone we can :trollface:

**Comment by paulyoung** [comment]
For some reason when using the command line the query parameters are in a different order which produces a different key.

Why this is only an issue on the command line and only an issue for iOS I'm not sure.

---

ClientSpec getting_a_URL__without_specifying_an_image_format__should_correctly_infer_the_format

```
https://imgflo.herokuapp.com/graph/key/7df11ca4fa37885489023ab263529f57/gradientmap.jpg?input=https://pbs.twimg.com/media/BlM0d2-CcAAT9ic.jpg:large&color1=%23ff0000&stop4=0.66&color4=%2300ff00&color5=%230000ff&srgb=true&stop2=0.33&stop1=0.17&color3=%23ffff00&stop3=0.5&stop5=0.83&color2=%23ff7f00
```

```
https://imgflo.herokuapp.com/graph/key/4892a9ef773cbdf85a860ebcb745d1ed/gradientmap.jpg?input=https://pbs.twimg.com/media/BlM0d2-CcAAT9ic.jpg:large&stop3=0.5&color1=%23ff0000&stop2=0.33&srgb=true&color4=%2300ff00&color2=%23ff7f00&stop5=0.83&color3=%23ffff00&stop4=0.66&color5=%230000ff&stop1=0.17
```

---

ClientSpec getting_a_URL__from_a_URL_without_an_extension__should_omit_the_format

```
https://imgflo.herokuapp.com/graph/key/2e7d1b8df004032d6e29783f0f43e790/gradientmap?input=https://lh6.ggpht.com/qhLc1KUYP3YpNUtf9MujZVld1ctgsU0_oEEqp6Jkte8hW1UNJqKSm9-ExP-uzyL3r2c%3Dh556&color1=%230a2a2f&srgb=true&stop2=1&stop1=0&color2=%23fde7a0
```

```
https://imgflo.herokuapp.com/graph/key/8cb3738c312cf2101b1ea1ae00ba34b0/gradientmap?input=https://lh6.ggpht.com/qhLc1KUYP3YpNUtf9MujZVld1ctgsU0_oEEqp6Jkte8hW1UNJqKSm9-ExP-uzyL3r2c%3Dh556&color1=%230a2a2f&stop2=1&srgb=true&color2=%23fde7a0&stop1=0
```

---

ClientSpec getting_a_URL__specifying_an_image_format__should_include_the_specified_format

```
https://imgflo.herokuapp.com/graph/key/6867ef481a315713663753147aa1b01d/gradientmap.png?input=https://pbs.twimg.com/media/BlM0d2-CcAAT9ic.jpg:large&color1=%23ff0000&stop4=0.66&color4=%2300ff00&color5=%230000ff&srgb=true&stop2=0.33&stop1=0.17&color3=%23ffff00&stop3=0.5&stop5=0.83&color2=%23ff7f00
```

```
https://imgflo.herokuapp.com/graph/key/0dd75072f7cce20ba80e6cd28b94f072/gradientmap.png?input=https://pbs.twimg.com/media/BlM0d2-CcAAT9ic.jpg:large&stop3=0.5&color1=%23ff0000&stop2=0.33&srgb=true&color4=%2300ff00&color2=%23ff7f00&stop5=0.83&color3=%23ffff00&stop4=0.66&color5=%230000ff&stop1=0.17
```

**Comment by paulyoung** [comment]
I fixed this by sorting the parameters in alphabetical order by key.

It's annoying to have to add this, but:
- The number of parameters is limited so the performance impact should be negligible.
- It adds confidence by having CI be able to run these tests.
- It opens up the potential for a shared set of fixtures for all imgflo libraries, provided they also sort in the same way.
